using Microsoft.Data.SqlClient;using QuanLyThueSanTheThao.Data;using QuanLyThueSanTheThao.Helpers;
namespace QuanLyThueSanTheThao.Forms.Admin;
public partial class FrmCustomers:Form
{
    private int? _id;
    public FrmCustomers(){InitializeComponent();AppTheme.Upgrade(this);ResponsiveHelper.Apply(this);try{var sp=this.Controls.OfType<System.Windows.Forms.SplitContainer>().FirstOrDefault(); if(sp!=null) ResponsiveHelper.FixSplitContainer(sp);}catch{}AppTheme.StyleGrid(grid);AppTheme.StyleSecondary(btnRefresh);AppTheme.StyleSecondary(btnNew);AppTheme.StylePrimary(btnSave);AppTheme.StyleDanger(btnDelete);AppTheme.StyleSecondary(btnAccount);grid.SelectionChanged+=(_,__)=>Bind();txtSearch.TextChanged+=(_,__)=>LoadData();btnRefresh.Click+=(_,__)=>LoadData();btnNew.Click+=(_,__)=>ClearForm();btnSave.Click+=(_,__)=>Save();btnDelete.Click+=(_,__)=>Delete();btnAccount.Click+=(_,__)=>CreateAccount();Shown+=(_,__)=>LoadData();}
    private void LoadData(){grid.DataSource=Db.Query(@"SELECT c.KhachHangID,c.MaKhachHang [Mã KH],c.HoTen [Họ tên],c.SoDienThoai [SĐT],c.Email,c.DiaChi [Địa chỉ],c.NgaySinh [Ngày sinh],c.DiemTichLuy [Điểm],u.TenDangNhap [Tài khoản],c.DangHoatDong [Hoạt động] FROM KhachHang c LEFT JOIN TaiKhoan u ON u.TaiKhoanID=c.TaiKhoanID WHERE @s='' OR c.MaKhachHang LIKE '%'+@s+'%' OR c.HoTen LIKE N'%'+@s+'%' OR c.SoDienThoai LIKE '%'+@s+'%' OR c.Email LIKE '%'+@s+'%' ORDER BY c.KhachHangID DESC",new SqlParameter("@s",txtSearch.Text.Trim()));if(grid.Columns.Contains("KhachHangID"))grid.Columns["KhachHangID"].Visible=false;}
    private void Bind(){if(grid.CurrentRow?.DataBoundItem is not System.Data.DataRowView rv)return;var r=rv.Row;_id=Convert.ToInt32(r["KhachHangID"]);txtCode.Text=Convert.ToString(r["Mã KH"]);txtName.Text=Convert.ToString(r["Họ tên"]);txtPhone.Text=Convert.ToString(r["SĐT"]);txtEmail.Text=Convert.ToString(r["Email"]);txtAddress.Text=Convert.ToString(r["Địa chỉ"]);if(r["Ngày sinh"]!=DBNull.Value)dtBirth.Value=Convert.ToDateTime(r["Ngày sinh"]);chkActive.Checked=Convert.ToBoolean(r["Hoạt động"]);}
    private void ClearForm(){_id=null;txtCode.Text="KH"+DateTime.Now.ToString("HHmmss");txtName.Clear();txtPhone.Clear();txtEmail.Clear();txtAddress.Clear();dtBirth.Value=DateTime.Today.AddYears(-18);chkActive.Checked=true;txtName.Focus();}
    private void Save(){if(string.IsNullOrWhiteSpace(txtCode.Text)||string.IsNullOrWhiteSpace(txtName.Text)){UiMsg.Warn("Nhập mã khách và họ tên.");return;}if(txtPhone.Text.Trim().Length>0&&(txtPhone.Text.Trim().Length<9||txtPhone.Text.Trim().Any(c=>!char.IsDigit(c)))){UiMsg.Warn("Số điện thoại phải có ít nhất 9 chữ số.");return;}try{var p=new[]{new SqlParameter("@c",txtCode.Text.Trim()),new SqlParameter("@n",txtName.Text.Trim()),new SqlParameter("@p",string.IsNullOrWhiteSpace(txtPhone.Text)?DBNull.Value:txtPhone.Text.Trim()),new SqlParameter("@e",string.IsNullOrWhiteSpace(txtEmail.Text)?DBNull.Value:txtEmail.Text.Trim()),new SqlParameter("@a",string.IsNullOrWhiteSpace(txtAddress.Text)?DBNull.Value:txtAddress.Text.Trim()),new SqlParameter("@d",dtBirth.Value.Date),new SqlParameter("@x",chkActive.Checked)};if(_id==null)Db.Execute("INSERT INTO KhachHang(MaKhachHang,HoTen,SoDienThoai,Email,DiaChi,NgaySinh,DangHoatDong) VALUES(@c,@n,@p,@e,@a,@d,@x)",p);else{var l=p.ToList();l.Add(new SqlParameter("@id",_id));Db.Execute("UPDATE KhachHang SET MaKhachHang=@c,HoTen=@n,SoDienThoai=@p,Email=@e,DiaChi=@a,NgaySinh=@d,DangHoatDong=@x WHERE KhachHangID=@id",l.ToArray());}LoadData();Toast.Success("Đã lưu khách hàng.");}catch(Exception ex){UiMsg.Error(ex.Message,"Lưu khách hàng");}}
    private void Delete(){if(_id==null||UiMsg.Ask("Xóa khách hàng này?", "Xác nhận", danger: true)!=DialogResult.Yes)return;try{var rows=Db.Execute("DELETE FROM KhachHang WHERE KhachHangID=@id AND TaiKhoanID IS NULL",new SqlParameter("@id",_id));if(rows==0){UiMsg.Warn("Khách đã có tài khoản nên không thể xóa. Hãy bỏ chọn Đang hoạt động rồi bấm Lưu để khóa hồ sơ.");return;}ClearForm();LoadData();Toast.Success("Đã xóa khách hàng.");}catch(Exception ex){UiMsg.Error("Không thể xóa khách đã có lịch sử giao dịch. Có thể khóa trạng thái.\n"+ex.Message);}}
    private void CreateAccount(){if(_id==null){UiMsg.Warn("Hãy chọn và lưu khách hàng trước.");return;}var linked=Convert.ToInt32(Db.Scalar("SELECT COUNT(*) FROM KhachHang WHERE KhachHangID=@id AND TaiKhoanID IS NOT NULL",new SqlParameter("@id",_id))??0);if(linked>0){UiMsg.Info("Khách hàng này đã có tài khoản đăng nhập.");return;}using var f=new Form{Text="Tạo tài khoản khách hàng",StartPosition=FormStartPosition.CenterParent,Size=new Size(450,260),FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false};var user=new TextBox{Left=28,Top=35,Width=380,PlaceholderText="Tên đăng nhập"};var pass=new TextBox{Left=28,Top=86,Width=380,PlaceholderText="Mật khẩu tối thiểu 6 ký tự",UseSystemPasswordChar=true};var b=new Button{Left=228,Top=148,Width=180,Height=42,Text="Tạo tài khoản"};AppTheme.StylePrimary(b);b.Click+=(_,__)=>{if(user.Text.Trim().Length<4||pass.Text.Length<6){UiMsg.Warn("Tên đăng nhập từ 4 ký tự và mật khẩu từ 6 ký tự.");return;}using var cn=Db.OpenConnection();using var tx=cn.BeginTransaction();try{var role=new SqlCommand("SELECT VaiTroID FROM VaiTro WHERE TenVaiTro=N'Customer'",cn,tx);var roleId=Convert.ToInt32(role.ExecuteScalar());var salt=Guid.NewGuid().ToString("N")[..16].ToUpperInvariant();var cmd=new SqlCommand("INSERT INTO TaiKhoan(TenDangNhap,MatKhauBam,MuoiMatKhau,VaiTroID,DangHoatDong) OUTPUT INSERTED.TaiKhoanID VALUES(@u,@h,@s,@r,1)",cn,tx);cmd.Parameters.AddWithValue("@u",user.Text.Trim());cmd.Parameters.AddWithValue("@h",PasswordHelper.Hash(salt,pass.Text));cmd.Parameters.AddWithValue("@s",salt);cmd.Parameters.AddWithValue("@r",roleId);var uid=Convert.ToInt32(cmd.ExecuteScalar());var link=new SqlCommand("UPDATE KhachHang SET TaiKhoanID=@u WHERE KhachHangID=@id AND TaiKhoanID IS NULL",cn,tx);link.Parameters.AddWithValue("@u",uid);link.Parameters.AddWithValue("@id",_id);if(link.ExecuteNonQuery()!=1)throw new InvalidOperationException("Hồ sơ vừa được liên kết ở cửa sổ khác.");tx.Commit();Toast.Success("Đã tạo tài khoản khách hàng.");f.Close();LoadData();}catch(Exception ex){try{tx.Rollback();}catch{}UiMsg.Error(ex.Message,"Tạo tài khoản");}};f.Controls.AddRange(new Control[]{user,pass,b});AppTheme.Upgrade(f);f.ShowDialogFx(this);}
}
